### ISSUE TITLE
Other potential mods to add to this:

### ISSUE THREAD

**Issue by Atlantispy** [gizmo-ds/smsn-mod#1]
Collective: https://www.curseforge.com/minecraft/mc-mods/collective

Obscure API: https://www.curseforge.com/minecraft/mc-mods/obscure-api

The Aether: https://www.curseforge.com/minecraft/mc-mods/aether

I believe all of these mods have some Patreon checks.

**Comment by gizmo-ds** [comment]
Thank you for the suggestion!

Here’s what I’ve found so far:

- **Collective**: After testing, I found that this mod does not send unnecessary network requests, so no action is needed.
- **Obscure API**: I have added handling for this mod in the latest update.
- **The Aether**: I haven’t tested this mod yet. If I confirm that it sends unnecessary network requests and they cannot be disabled through configuration, I will include handling for it in a future update.

Thank you again for bringing these to my attention! Let me know if you have any further details about The Aether or other mods.

**Comment by Atlantispy** [comment]
I've merely based it off knowing they have some form of Patreon reward/thanking.

It may be the case that they are built in rather than querying a website for it.

The Aether I believe has Moa (a mount) reward skins for Patreons, and I couldn't see an easy way to configure it.

**Comment by gizmo-ds** [comment]
I’ve released version [1.1.0](https://github.com/gizmo-ds/smsn-mod/releases/tag/v1.1.0%2Bmc1.20.1), which includes handling for **The Aether**. By default, this specific feature is not disabled to respect its functionality. However, I’ve added a configuration file (`smsn.json5`) where you can set `aetherMoaSkinsFeature` to `false` if you wish to block the network requests related to the Patreon Moa skins feature.
