### ISSUE TITLE
Other potential mods to add to this: 

### ISSUE THREAD

**Issue by enjoyable1** [gizmo-ds/smsn-mod#2]
I've found that this behavior happens with “botania” as well.  It always seems to delay me by 4000ms.  in actuality I don't know if it's because of the delay it triggers, I didn't test it, I just saw the message that the fetch failed.  I didn't find a config in botania to turn it off.  Would you like to add to block the fetch behavior of this mod？

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a new configuration option to disable Botania's contributor check, similar to other mods in the project. This includes updating the ModConfig interface, ModConfigData, and ModConfigDefaults classes to include the new option. Also added a new mixin class to intercept and potentially block Botania's web requests.

You can review changes in this commit: https://github.com/jjyutm4532/gizmo-ds-smsn-mod-2/commit/5a4be41dcb8276508e8b389e92541334907b90b5.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by gizmo-ds** [comment]
After reviewing **Botania**, I confirmed that it has network requests that cannot be disabled through its configuration. I’ll add handling for this in the next version. 

https://github.com/VazkiiMods/Botania/blob/ce987df1e4af39971863c41ac7368127ef9b2522/Xplat/src/main/java/vazkii/botania/common/handler/ContributorList.java#L118

**Comment by enjoyable1** [comment]
This is great.
